name: Stage the app

on:
  pull_request:
    types: [labeled] # Trigger on labeling events

jobs:
  build:
    runs-on: ubuntu-latest

    # Only run this job if the 'stage' label is added to the PR
    if: contains(github.event.pull_request.labels.*.name, 'stage')